name: Build macOS App

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build .app with PyInstaller
        run: |
          pyinstaller \
            --windowed \
            --name "ScreenRight" \
            --icon=ScreenRight.icns \
            --onefile \
            --clean \
            screen_right.py

      - name: Verify .app exists
        run: |
          ls -R dist/
          if [ ! -d "dist/ScreenRight.app" ]; then
            echo "ScreenRight.app not found!"
            exit 1
          fi

      - name: Upload built .app
        uses: actions/upload-artifact@v3
        with:
          name: Mac-App
          path: dist/ScreenRight.app
