name: Create Executable
on: [push]
jobs:
  pyinstaller-build:
    runs-on: windows-latest
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1.8.0
        with:
          python_ver: '3.11.4'
          spec: 'ScreenRight.spec'
          requirements: 'requirements.txt'
          upload_exe_with_name: ''
      - name: Copy parameters file
        run: copy parameters.txt dist/parameters.txt        
      - name: Upload Executable
        uses: actions/upload-artifact@v4
        with:
          name: 'ScreenRight'
          path: './dist'
          compression-level: 6